#configuration postgres

spring:
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  #configuration Spring Data Jpa

  #jpa:
  #  show-sql: true
  #  hibernate:
  #    ddl-auto: create-drop
  #database-platform: org.hibernate.dialect.PostgreSQLDialect




